# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='submitter',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='quotes.User'),
            preserve_default=False,
        ),
    ]
